name: deploy CD

on:
  push:
    tags:
      - v\d+\.\d+\.\d+

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20.7.0

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo -n '${{ secrets.GCS_DR }}' > dev.json
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run uploadGcs
